--- # EC2 provising
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yml
  tasks:
  - name: Basic provisiong of two t2.micro Ec2 instance
    ec2:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     image: <ami_id>
     instance_type: t2.micro
     count: 2
     assign_public_ip: yes

